# Generated by Django 4.2.2 on 2024-08-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Token"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите свой аватар",
                null=True,
                upload_to="users/avatars",
                verbose_name="Аватар (Не обязательно)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=50, verbose_name="Страна (Обязательно)"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Введите номер телефона",
                max_length=40,
                null=True,
                verbose_name="Телефон (Не обязательно)",
            ),
        ),
    ]
