# Generated by Django 5.0.6 on 2024-07-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materials",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовать"),
        ),
        migrations.AlterField(
            model_name="materials",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
        ),
    ]
