# Generated by Django 5.0.6 on 2024-07-29 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.CharField(max_length=50)),
                ("version_name", models.CharField(max_length=255)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
                "ordering": ["-is_current", "version_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("product", "is_current"),
                name="unique_current_version",
            ),
        ),
    ]
