# Generated by Django 5.0.6 on 2024-08-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_version_version_unique_current_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_current",
            field=models.BooleanField(default=False, verbose_name="Текущая версия"),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_name",
            field=models.CharField(max_length=255, verbose_name="Название версии"),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.CharField(max_length=50, verbose_name="Номер версии"),
        ),
    ]
