# Generated by Django 4.2.2 on 2024-08-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["description", "name"],
                "permissions": [
                    ("can_change_description", "Can change description"),
                    ("can_change_category", "Can change category"),
                    ("can_change_is_published", "Can change is_published"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовать"),
        ),
    ]
